next.config.js
package.json
pnpm-lock.yaml
src/app/layout.tsx
src/app/page.tsx
src/app/providers.tsx
src/components/MainPage/index.tsx
src/components/MentorCard/index.tsx
src/components/MentorList/index.tsx
src/components/WorkerListItem/index.tsx
src/hooks/api/index.ts
src/hooks/api/mentor/index.ts
src/hooks/api/mentor/useGetMentorList.ts
src/hooks/index.ts
src/libs/api/axiosInstance.ts
src/libs/api/http.ts
src/libs/api/index.ts
src/libs/api/queryKeys.ts
src/libs/api/requestUrlController.ts
src/libs/index.ts
src/types/worker.ts

신서버 API 연동을 위한 밑 작업을 했습니다.
- 의존성 설치
- axios, @tanstack/react-query, @tanstack/react-query-devtools
- requestUrlController 추가
- queryKey 중복 방지 위한 queryKeys 단일 파일 관리
- http method에 맞게끔 custom function 제작

Api Setting

---

src/components/SearchBar/style.ts

> 괄호의 개수가 맞지 않는것같아 수정했습니다.
괄호의 개수가 맞지 않는것같아 수정했습니다.

Fix(search bar): delete bracket

---

src/constants/generation.ts
src/constants/index.ts
src/constants/month.ts
src/constants/position.ts
src/constants/year.ts

여러 모듈들에서 사용될 상수를 선언하였습니다.
- generation 상수 선언
- month 상수 선언
- position 상수 선언
- year 상수 선언

Add constants

---

next.config.js
package.json
pnpm-lock.yaml

register form을 위한 의존성들을 설치했습니다.
- Remove styledConponents option in next config
- Add dependencies
- @hookform/resolvers
- react-hook-form
- zod

Add Dependencies

---

src/assets/TriangleIcon.tsx
src/assets/index.ts
src/components/MentorCard/index.tsx
src/components/MentorCard/style.ts
src/components/ToolTip/index.stories.tsx
src/components/ToolTip/index.tsx
src/components/ToolTip/style.ts

> 멘토인 유저의 블루쳌에 띄워지는 ToolTip을 제작했습니다.
hover시 ToolTip이 보여집니다.

Add toolTip

---

src/utils/__test__/deepCopy.test.ts
src/utils/deepCopy.ts
src/utils/index.ts

deepCopy util을 제작했습니다.
깊은 복사를 위한 deepCopy util을 제작했습니다.

Add deepCopy

---

src/components/Select/index.stories.tsx
src/components/Select/index.tsx
src/components/Select/style.ts
src/components/index.ts
src/hooks/index.ts
src/hooks/useForwardRef.ts

Select component를 추가했습니다.
- Select component 추가
- ref prop을 전달하기 위한 useForwardRef hook 추가

Add select component

---

src/components/Header/index.tsx
src/components/Header/style.ts

Header에 홈 링크를 추가했습니다.
- Header에 홈(/) 링크 추가

Add Home link at Header

---

src/components/Header/index.tsx
src/components/Header/style.ts
src/components/InfoSearch/style.ts

qa에 사용한 멘토 데이터 삭제를 서비스상 제거합니다.
- 멘토 데이터 삭제 로직 서비스상 제거
- 추후에 prod에 도입 가능성이 있어 관련 코드는 남기고, 서비스에서 보여지지 않게끔 하겠습니다.
- header `멘토 컨택` 클릭 시, 준비중 피드백 추가 
- /register/search input focus 시의 outline 스타일 추가

Remove delete mentor data

---

src/components/Header/index.tsx
src/components/Header/style.ts

coming soon toast를 프로필 클릭 시 띄웁니다.
- handleMentorContactClick => comingSoonToast 함수 명 변경
- ProfileBox onClick에 comingSoonToast 추가

Add coming soon toast at profile

---

.vscode/settings.json
src/pageContainer/signup/index.tsx

/auth/signup 멘토 선택 시의 이동되는 주소를 변경했습니다.
/auth/signup 멘토 선택 시
/register/mentor -> /register/search 로 변경되었습니다.

[Hotfix] Update signup/mentor URL

---

src/components/CareerCard/index.stories.tsx
src/components/CareerCard/index.tsx
src/components/CareerCard/style.ts
src/components/index.ts

> 마이페이지에 있는 재직 정보 컴포넌트를 만들었습니다
> 재직 중이 아닐때
> 재직 중 일때
<br>
<br>
> Add index.tsx, Add style.ts, Add index.stories.tsx

Add careerCard

---

src/components/CareerCard/index.stories.tsx

story에서 타입 에러로 인해 빌드가 실패하는 현상을 해결했습니다
- CareerCard story build error 해결

Resolve build error

---

src/components/UserStatusSelect/index.tsx

회원 가입 시, 유저 상태 등록 페이지에서 멘티 권한의 예시로 선생님도 추가했습니다.
- UserStatusSelect에 선생님 예시 추가

Add teacher example

---

src/pageContainer/register/mentor/index.tsx

멘토 등록 이후, 메인페이지로 이동하는 로직 추가
- handleMentorRegisterSuccess에 main 페이지 이동 로직 추가

[Hotfix] Add redirect logic at mentor register onSuccess

---

src/components/Header/index.tsx
src/components/Header/style.ts

커뮤니티 런칭을 위해 Header nav를 업데이트 했습니다.
- 커뮤니티 광야 링크 추가
- 기존 commingSoon 함수 제거
- 멘토 컨택 버튼 제거

Update header for communify

---

src/hooks/api/gwangya/useGetGwangyaPostList.ts
src/pageContainer/gwangya/index.tsx
src/pageContainer/gwangya/style.ts

- useGetGwangyaPostList(useInfiniteQuery) 의 초기값(initailData)이 덮어 씌워지는 현상이 발생하여 해결하였습니다.
- https://github.com/TanStack/query/discussions/1648 해당 discussions 참고하여 staleTime을 설정해주어 해결했습니다.

[Hotfix] Resolve Gwangya Post List error

---

.vscode/settings.json
src/components/CommunityCard/style.ts

>  Community Car중, 불필요한 Padding부분을 삭제시켰습니다.
> Fix community card padding area

Fix paddingArea

---

src/assets/GoBackIcon.tsx
src/assets/index.ts
src/components/ChattingHeader/index.stories.tsx
src/components/ChattingHeader/index.tsx
src/components/ChattingHeader/style.ts

> chatting header를 만들었습니다
> Add GoBackIcon, Add index.tsx ...
> 뒤로가기 버튼 클릭시 이동될 경로가 정해지지 않았습니다

Add chatting header

---

src/apis/index.ts
src/apis/mentee/getMyMenteeInfo.ts
src/apis/mentee/index.ts
src/app/page.tsx
src/components/MainPage/index.tsx
src/hooks/api/mentee/index.ts
src/hooks/api/mentee/useGetMyMenteeInfo.ts
src/libs/api/queryKeys.ts
src/libs/api/requestUrlController.ts
src/pageContainer/register/mentee/index.tsx

> 현재 기존 멘티가 멘티 등록 기능에 접근 할 수 있는 방법이 존재하지 않아 기능을 추가했습니다.
멘티 권한을 가진 유저 && 멘티 정보가 없는 유저
라면 접속 시 멘티 정보 등록 페이지로 리다이렉트 시킵니다.
- useGetMyMenteeInfo 개발
- getMyMenteeInfo 개발

[Hotfix] mentee register redirect

---

src/apis/mentee/getMyMenteeInfo.ts

[Hotfix] Update blockRedirect

---

src/constants/menteeGeneration.ts

> mentee 기수에 8기를 추가하였습니다
> Update menteeGeneration.ts

Add 8 generation

---

src/apis/mentee/getMyMenteeInfo.ts
src/components/CareerRegistrationBox/index.tsx
src/constants/year.ts

> 현재 연도와 월에 select가 영향을 받도록 하였습니다.
- getMonthArray 함수를 제작하였습니다.
연도가 선택된 후에 월을 선택할 수 있습니다. 선택된 연도가 현재 연도와 같다면 선택 가능한 월만 리턴합니다.
- 현재 연도에 따라 동적으로 연도 배열이 설정되도록 하였습니다.

[Hotfix] Update year select

---

src/apis/index.ts
src/apis/mentee/getMyMenteeInfo.ts
src/apis/mentee/index.ts
src/app/page.tsx
src/components/Buttons/ChattingButton/index.stories.tsx
src/components/Buttons/ChattingButton/index.tsx
src/components/Buttons/ChattingButton/style.ts
src/components/CareerRegistrationBox/index.tsx
src/components/CommunityCard/index.tsx
src/components/MainPage/index.tsx
src/constants/menteeGeneration.ts
src/constants/year.ts
src/hooks/api/mentee/index.ts
src/hooks/api/mentee/useGetMyMenteeInfo.ts
src/libs/api/queryKeys.ts
src/libs/api/requestUrlController.ts
src/pageContainer/register/mentee/index.tsx

Add chattingButton

---

src/apis/index.ts
src/apis/mentee/getMyMenteeInfo.ts
src/apis/mentee/index.ts
src/app/page.tsx
src/components/CareerRegistrationBox/index.tsx
src/components/CommunityCard/index.tsx
src/components/MainPage/index.tsx
src/components/MiniProfile/index.stories.tsx
src/components/MiniProfile/index.tsx
src/components/MiniProfile/style.ts
src/constants/menteeGeneration.ts
src/constants/year.ts
src/hooks/api/mentee/index.ts
src/hooks/api/mentee/useGetMyMenteeInfo.ts
src/libs/api/queryKeys.ts
src/libs/api/requestUrlController.ts
src/pageContainer/register/mentee/index.tsx

> 작은 프로필을 추가했습니다.
- main을 merge 받으며 변경사항이 생겼습니다.

Add MiniProfile

---

src/components/CommentCard/index.stories.tsx
src/components/CommentCard/index.tsx
src/components/CommentCard/style.ts
src/components/MiniProfile/index.stories.tsx
src/components/MiniProfile/index.tsx
src/components/MiniProfile/style.ts
src/components/index.ts
src/types/comment.ts
src/types/index.ts
src/types/profile.ts

> 댓글 카드를 제작했습니다.
재귀 컴포넌트를 활용해 대댓글을 구현했습니다.
- default style
- mentioned
- replied

Add commentCard

---

src/app/community/board/[postId]/[commentId]/page.tsx
src/components/CommentCard/index.tsx
src/pageContainer/community/board/detail/comment/index.tsx
src/pageContainer/community/board/detail/comment/style.ts
src/pageContainer/community/board/detail/index.tsx
src/pageContainer/index.ts

> 댓글 추가 페이지를 제작했습니다.
http://localhost:3000/community/board/n/n 에서 확인하실 수 있습니다.

Add addCommentPage

---

src/components/Modal/Filter/style.ts

Update filter modal position

---

src/pageContainer/community/write/index.tsx

게시글 작성 성공 시, 이동되는 페이지 url 수정했습니다.
- 게시글 작성 성공 시, 이동되는 페이지 주소 `/community` => `/community/board` 수정

Update usePostBoardContent onSuccess push url

---

src/app/page.tsx
src/components/CommentCard/index.stories.tsx
src/components/MentorCard/RandomMentorImg/index.stories.tsx
src/components/MentorCard/RandomMentorImg/index.tsx
src/components/MentorCard/index.stories.tsx
src/components/MentorCard/index.tsx
src/components/MiniProfile/index.stories.tsx
src/components/MiniProfile/index.tsx
src/components/Profile/index.tsx
src/components/TempMentorCard/index.stories.tsx
src/hooks/api/mentee/usePostMenteeRegister.ts
src/hooks/api/mentor/usePostMentorRegister.ts
src/hooks/api/mentor/usePutMentorUpdate.ts
src/pageContainer/mypage/index.tsx
src/pageContainer/register/mentor/index.tsx
src/types/board.ts
src/types/mentee.ts
src/types/mentor.ts
src/types/mentorInfo.ts
src/types/profile.ts
src/types/worker.ts

> 멘토, 멘티 타임에 defaultImgNumber 필드를 추가했습니다.
defaultImgNumber 필드가 추가됨에 따라 MentorRequestType, MenteeRequestType이 추가되었습니다.
이 변경사항에 따른 side effect가 없는지 확인 부탁드립니다.

Update mentor, mentee type

---

src/app/community/board/page.tsx

> Opengraph
> Opengraph 작업하였습니다

Add openGraph

---

src/components/BoardCard/style.ts
src/pageContainer/community/board/detail/comment/style.ts
src/pageContainer/community/board/detail/style.ts

> 게시판 페이지의 반응형 문제를 고쳤습니다.
- 게시판 페이지에서 가로 스크롤이 되는 문제를 해결했습니다.
- 게시판 상세 페이지에서 가로 스크롤이 되는 문제와 상하 스크롤이 완전히 되지 않는 문제를 해결했습니다.

[Hotfix] Fix board responsive

---

package.json
pnpm-lock.yaml
src/app/providers.tsx
src/components/BoardCard/style.ts
src/components/Buttons/CommunityButton/index.tsx
src/components/Buttons/WriteButton/style.ts
src/components/Header/style.ts
src/components/InfoSearch/style.ts

> page transition을 추가했습니다.
https://github.com/themoment-team/GSM-Networking-front/assets/106712562/ac177139-85a3-43bd-91f8-b7aadd9130fc

Add page transition

---

src/app/community/board/[boardId]/[commentId]/page.tsx
src/app/community/board/[boardId]/page.tsx
src/components/BoardCard/index.tsx
src/pageContainer/community/board/detail/comment/index.tsx
src/pageContainer/community/board/detail/index.tsx
src/pageContainer/community/write/index.tsx

> 토큰 만료 시에 board page에 접속하면 /board로 리다이렉트 되는 문제가 있었습니다. 이를 해결했습니다.
상수로 선언되어있던 BOARD_PATH를 각 부분마다 사용하여 안정성을 높였습니다.

[Hotfix] Update boardPath

---

src/components/Header/index.tsx
src/components/Header/style.ts
src/pageContainer/community/board/detail/index.tsx
src/pageContainer/community/board/detail/style.ts
src/pageContainer/community/board/style.ts
src/types/header.ts
src/types/index.ts

https://github.com/themoment-team/GSM-Networking-front/assets/128475660/712e0107-6bfd-4efc-97a7-29df7ca14aac
여러가지 css를 수정했습니다
- 광야 | 게시판 button margin 수정
- header props 추가
- HeaderPosition Enum 추가
브랜치를 hotfix로 만들지 않고 feature로 만들어버렸습니다 죄송합니다

[Hotfix] Update CSS

---

src/apis/board/comment/getCommentDetail.ts
src/apis/board/getBoardDetail.ts
src/app/auth/refresh/route.ts
src/app/community/board/[boardId]/[commentId]/page.tsx
src/app/community/board/[boardId]/page.tsx
src/app/page.tsx
src/app/providers.tsx
src/components/BoardCard/index.tsx
src/components/BoardCard/style.ts
src/components/Header/index.tsx
src/components/Header/style.ts
src/pageContainer/community/board/detail/comment/index.tsx
src/pageContainer/community/board/detail/comment/style.ts
src/pageContainer/community/board/detail/index.tsx
src/pageContainer/community/board/detail/style.ts
src/pageContainer/community/board/style.ts
src/pageContainer/community/write/index.tsx
src/types/header.ts
src/types/index.ts
src/utils/deleteCookie.ts
src/utils/index.ts

> Hotfix changes -> develop
> Hotfix변경사항을 develop으로 가져왔습니다

Hotfix changes -> develop

---

src/components/BoardCard/index.tsx
src/components/BoardCard/style.ts
src/components/Buttons/LikeButton/index.tsx
src/components/Buttons/LikeButton/style.ts
src/pageContainer/community/board/style.ts

> Delete list like button
> 리스트의 좋아요 버튼 동작을 불가하게 했습니다 + gap 수정

[hotfix] Delete list like button

---

src/components/Header/index.tsx
src/components/Header/style.ts
src/components/Modal/MyPage/DefaultProfileSelect/index.tsx

> 기본 프로필 변경시 refetch를 추가하였습니다
https://github.com/themoment-team/GSM-Networking-front/assets/128475660/50427c10-2b99-45b1-b4c9-0a73c78a3a4d
- refetch 추가
- style 수정

[Hotfix] Update profile

---

src/components/Header/index.tsx

0번 default profile img로 변경시 header에 profile에 뜨지 않는 문제를 해결하였습니다
- if문 수정

[Hotfix] Header Profile Update

---

src/app/community/write/page.tsx
src/components/Header/style.ts
src/components/Modal/MyPage/DefaultProfileSelect/index.tsx
src/constants/communityCategory.ts
src/hooks/api/board/index.ts
src/hooks/api/board/usePatchBoard.ts
src/libs/api/queryKeys.ts
src/libs/api/requestUrlController.ts
src/pageContainer/community/board/detail/index.tsx
src/pageContainer/community/board/detail/style.ts
src/pageContainer/community/write/index.tsx
src/pageContainer/mypage/index.tsx
src/types/author.ts
src/types/board.ts
src/types/index.ts
src/types/mentee.ts
src/types/mentor.ts
src/utils/index.ts
src/utils/isMyBoard.ts

게시글 수정기능을 제작하였습니다
- author 타입 제작
- usePatchBoard 제작
- isMyBoard 제작
- 수정 버튼 제작

[게시판] 게시글 수정기능 추가

---

src/app/community/board/teacher/page.tsx
src/components/BoardList/index.tsx
src/components/BoardList/style.ts
src/components/Modal/BoardFilter/index.tsx
src/components/index.ts
src/hooks/api/board/useGetBoardList.ts
src/libs/api/requestUrlController.ts
src/pageContainer/community/board/index.tsx
src/pageContainer/community/board/style.ts
src/pageContainer/community/board/teacher/index.tsx
src/types/category.ts

> 게시판 필터 로직을 적용하고 BoardList를 컴포넌트로 분리하여 책임을 나누고, 재사용성을 높였습니다.
- BoardList 컴포넌트 분리
- API 쿼리 스트링 key 변경

[게시판] 필터 적용 및 BoardList 컴포넌트 분리

---

src/components/BoardCard/index.tsx
src/components/Header/index.tsx
src/hooks/index.ts
src/hooks/useCheckIsTeacher.ts
src/pageContainer/community/board/teacher/index.tsx
src/pageContainer/community/write/index.tsx

> 선생님이 아닌 경우에도 선생님 게시판에서 글쓰기 버튼이 노출됨을 확인하여 예외처리 하였습니다.
- `useCheckIsTeacher` hook을 제작하여 기존 중복되는 코드들을 간소화 시켰습니다.
before ->

[게시판] 선생님이 아닌 경우 글 작성 예외처리

---

src/components/Modal/FileUpload/FileUploadModal/index.tsx

파일 업로드 시에 이전 파일이 사라지는 문제를 해결했습니다.
파일 업로드 시에 이전 파일이 사라지는 문제를 해결했습니다.

[게시판] 파일 업로드 시 이전 파일 유지.

---

src/app/mypage/page.tsx
src/pageContainer/mypage/index.tsx

> 마이페이지에서 전화번호가 정상적으로 처리되지 않아 오류가 발생한 것으로 파악했습니다. 이를 확인하기 위해 예외 처리 코드를 추가했습니다.
- 전화번호가 존재할 때에만 slice가 실행되도록 조건부 렌더링 하였습니다.

[Hotfix] 전화번호 예외처리 추가

---

src/components/Header/index.tsx

0 값을 가진  프로필 캐릭터가 보이지 않는 문제를 해결하였습니다
- header profile을 띄우는 조건식을 수정하였습니다

[Hotfix] header profile 부분 조건식 수정

---

src/components/MentorCard/index.tsx
src/pageContainer/community/board/detail/index.tsx

hotfix: 채팅 바로가기 기능 주석 처리

---

src/components/MentorList/Header/index.tsx
src/components/Modal/Filter/index.tsx
src/types/generation.ts
src/utils/__test__/deepCopy.test.ts

제목과 같습니다.
==============
> 이 pr의 목적을 적어주세요
> 이 pr에서 작업한 내용을 적어주세요
> 관련된 issue를 적어주세요(없다면 이 부분은 삭제 해주세요)

chore: 필터링 기수 배열 확장
