themoment-team/GSM-Networking-front

src/app/page.tsx
src/hooks/api/index.ts
src/libs/api/requestUrlController.ts

멘토 가져오기 api를 신서버로 전환했습니다.
- getMentorList api 신서버 전환
- mainpage Worker => Mentor 키워드 업데이트
- 모든 Worker 키워드를 한번에 Mentor로 전환하기에는 다른 작업 중인 부분들에 미칠 side effect가 크다고 판단되어 점진적으로 업데이트 하겠습니다.

getMentorList new server migration

---

src/hooks/api/mentor/usePostMentorRegister.ts
src/libs/api/queryKeys.ts
src/libs/api/requestUrlController.ts
src/types/career.ts
src/types/index.ts
src/types/mentor.ts

멘토 등록을 위한 react query hook을 제작했습니다.
- usePostMentorRegister 제작
- postCreateMentor -> postMentorRegister 용어 변경
- MentorType 추가
- CareerType 추가

Add usePostMentorRegister

---

src/components/FormItemWrapper/index.stories.tsx
src/components/FormItemWrapper/index.tsx
src/components/FormItemWrapper/style.ts
src/components/index.ts

FormItemWrapper를 제작하였습니다.
멘토 등록 폼에 사용 될, FormItemWrapper를 제작했습니다.
input이나 select 같은 form item들의 공통 부분을 FormItemWrapper으로 작성해두어 재사용성을 높입니다.
storybook
http://localhost:6006/?path=/story/components-formitemwrapper--primary
을 통해 확인 가능하십니다.

Add FormItemWrapper

---

src/utils/UTCDate.ts
src/utils/__test__/UTCDate.test.ts
src/utils/index.ts

UTCDate util을 추가했습니다
Date 객체를 api 요청에 담아 보내게 되면 아래 사진과 같이,
UTC로 변환되어 전송이 되어 예상치 못한 혼동이 생길 수 있습니다.
따라서 환경에 구애받지 않는 UTC 형식의 Date 객체를 생성하는 util을 사용하여
재직년월 등록 시 발생할 수 있는 혼동을 막도록 하겠습니다

Add UTCDate

---

src/components/CareerRegistrationBox/index.tsx
src/components/FormItem/Input/style.ts
src/components/InfoSearch/style.ts
src/components/Select/style.ts
src/pageContainer/register/mentor/index.tsx
src/styles/GlobalStyle.tsx

iOS 대응 및 input의 placeholder를 추가했습니다.
- globalstyle에서 input 모바일 시, 16px로 font size를 지정했습니다.
- iOS에서 input의 font size가 16px 미만일 시, input이 focus 되면 확대가 되는 현상이 있어 해결했습니다.
- input들의 누락된 placeholder를 추가했습니다.
- input들의 누락된 placeholder의 typo를 추가했습니다.

Add iOS compatible & input placeholder

---

src/app/page.tsx

main 페이지의 server side fetching에서의 error handling 방식을 업데이트 했습니다.
- try...catch 문으로 인해 next/navigation redirect를 사용하기 쉽지 않아 try...catch를 제거 했습니다
- try 내부에서 next/navigation redirect 사용 시, 내부적으로 error를 발생시켜 catch 문이 동작하는 현상이 존재합니다.
- https://stackoverflow.com/questions/76191324/next-13-4-error-next-redirect-in-api-routes
- https://github.com/vercel/next.js/blob/canary/packages/next/src/client/components/redirect.ts#L16-L41C2
- 401 - /auth/refresh
- 403 - /auth/signup
- 이 외 - /auth/signin

[Hotfix] Update main fetching error handling

---

src/pageContainer/signup/index.tsx
src/pageContainer/signup/style.ts

개인정보 처리방침 본문 확인 링크를 별도로 분리했습니다.
- 개인정보 처리방침 본문 확인 링크 별도 분리
기존 방식의 문제점
- 개인정보 처리방침 텍스트가 라벨의 역할을 하는 것 처럼 보여 유저들이 체크를 하기 위해 누르는 경우가 있다.
- 모바일에서 잘 못 클릭되어 해당 페이지로 이동되는 경우가 많다.
위의 문제점을 개선하고자 분리합니다
- 개인정보 처리방침 텍스트는 이제, label의 역할을 하여 체크를 위해 사용됩니다.
- 본문 확인을 누르면 약관 페이지로 이동합니다

[Hotfix] Update signup agreement box

---

src/app/mypage/page.tsx
src/components/CareerCard/index.stories.tsx
src/components/CareerCard/index.tsx
src/components/Header/index.tsx
src/components/Profile/index.tsx
src/hooks/api/mentor/useGetMyInfo.ts
src/pageContainer/mypage/index.tsx
src/pageContainer/register/mentor/index.tsx
src/types/career.ts
src/types/mentor.ts

> `useGetMyInfo`를 mypage에 적용했습니다.
- `CareerType`의 `Date`들이 `string`으로 변경됨에 따라 `RequestCareerType`과 `CareerType`으로 분리했습니다.
- `mypage`에서 `2023-11-20`을 `2023.11`로 변환해주는 `convertDate`를 제작했습니다.

Apply useGetMyInfo

---

next.config.js
src/components/Buttons/ProfileUpdate/index.tsx
src/components/Header/index.tsx
src/components/Header/style.ts
src/components/MentorCard/index.stories.tsx
src/components/MentorCard/index.tsx
src/components/MentorCard/style.ts
src/components/Modal/MyPage/ModalWrapper/index.tsx
src/components/Modal/MyPage/ModalWrapper/style.ts
src/components/Modal/MyPage/ProfileImgRegister/index.tsx
src/components/Profile/index.tsx
src/components/Profile/style.ts
src/components/TempMentorCard/index.stories.tsx
src/hooks/api/file/index.ts
src/hooks/api/file/usePostUploadFile.ts
src/hooks/api/index.ts
src/hooks/api/user/index.ts
src/hooks/api/user/usePostProfileImgUrl.ts
src/libs/api/queryKeys.ts
src/libs/api/requestUrlController.ts
src/pageContainer/mypage/index.tsx
src/types/index.ts
src/types/profile.ts
src/types/worker.ts

프로필 이미지 등록 api 연동 했습니다.
- 외부 이미지 사용을 위한 next.config.js image 속성 추가
- profileUrl로 멘토 이미지 보여지도록 했습니다
- Header
- MentorCard
- Profile
- 이미지를 업로드하는 usePostUploadFile 추가
- 이미지 url을 업로드하는 usePostProfileImgUrl 추가
1. usePostUploadFile로 이미지를 업로드합니다.
2. 1의 응답으로 받은 fileUrl을 담아 usePostProfileImgUrl 이미지 url 등록 요청을 보냅니다.
3. useGetMyInfo의 refetch로 갱신된 내 정보 데이터를 다시 받아옵니다

Add profile image register api

---

src/app/community/gwangya/page.tsx
src/pageContainer/gwangya/index.tsx
src/pageContainer/gwangya/style.ts
src/pageContainer/index.ts

커뮤니티 - 광야의 페이지 틀을 제작했습니다.
- pageContainer/gwangya 추가
- app/community/gwangya/page.tsx 추가

Add gwangya page 

---

src/components/CareerRegistrationBox/index.tsx

- 재직 중 클릭 시, 모든 경력이 재직 상태로 변경되는 에러가 발생했습니다
객체를 복사할 때, 얕은 복사가 되어 이런 에러가 발생하였고,
깊은 복사 방식으로 변경하여 해당 현상이 발생하지 않습니다

Hotfix Register tenure Error

---

src/app/auth/refresh/gwangya/route.ts
src/app/page.tsx
src/libs/api/axiosInstance.ts
src/libs/api/requestUrlController.ts
src/types/gwangya.ts
src/types/index.ts

광야 서비스를 위한 gwangya token 로직을 추가했습니다.
- client side fetching 
- axios request interceptor에서 gwangya token 발급/갱신
- server side fetching
- /auth/refresh/gwanya/route.ts에 gwangya token 발급/갱신
- 현재는 Home말고는 마땅히 사용할 부분이 없어 Home 이외 다른 페이지에는 추가하지 않았습니다.
- 추후에 gwangya page에도 추가하여 페이지 진입 전, gwangya token 발급/갱신 및 token 없는 회원 필터링 구현하겠습니다.
1, /mypage 직접 접근 시(client side fetching), gwangyaToken 잘 발급되는지 확인
2. / 직접 접근 시(server side fetching), gwangyaToken 잘 발급되는지 확인

Add gwangya token logic

---

src/app/community/gwangya/page.tsx
src/components/TextArea/style.ts
src/hooks/api/gwangya/useGetGwangyaPostList.ts
src/hooks/index.ts
src/hooks/useGetRem.ts
src/pageContainer/gwangya/index.tsx
src/pageContainer/gwangya/style.ts

useGetGwangyaPostList의 단순 연동 상태에서 무한 스크롤을 적용하기 위해 useQuery => useInfiniteQuery 마이그레이션을 했습니다.
- `/community/gwangya` server side fetching 추가
- token 검증 및 token 유무에 따른 리다이렉트 
- useGetGwangyaPostList의 initial data로 해당 응답을 할당함
- useQuery => useInfiniteQuery 마이그레이션
- https://tanstack.com/query/latest/docs/react/reference/useInfiniteQuery
- 서비스 특성 상 getNextPageParam이 아닌, getPreviousPageParam 및 fetchPreviousPage을 사용합니다.
- 1rem 값을 가져오는 useGetRem hook 추가
1. IntersectionObserver로 LoadMoreTrigger를 관찰합니다.
2. 뷰포트에 LoadMoreTrigger가 노출되면 관찰을 멈춥니다. 
3. fetchPreviousPage를 호출합니다.
4. 다시 관찰을 시작합니다.
상단으로 스크롤하여 이전 게시글들을 가져온 이후, 
스크롤이 상단에 고정된 상태가 유지되어,
LoadMoreTrigger가 노출된 상태가 유지되어 1, 2, 3 .. page들을 중단없이 가져와버리는 현상이 발생했습니다.
따라서 아래 코드를 통해
fetching 이후 수동으로 새로 받아온 리스트의 첫 게시글(이전 페이지의 마지막 게시글) 부근으로 스크롤 되도록 코드로 …

Migrate useGetGwangyaPostList useQuery => useInfiniteQuery

---

src/app/auth/refresh/gwangya/route.ts
src/app/page.tsx
src/components/CommunityCard/index.tsx
src/components/CommunityCard/style.ts
src/hooks/api/gwangya/useGetGwangyaPostList.ts
src/libs/api/axiosInstance.ts

CommunityCard Date 객체 생성 방식을 변경하였습니다.
- api에서 반환되는 createdAt이 UTC 형식으로 반환되어 Date 객체 생성 시, UTC 시간대 임을 표기해줍니다
- 잘못된 refresh logic 들의 refresh path 수정
- CommunityCard의 content tag를 p => pre 로 변경
- gwangya api 요청 여부 검증 path 변경
- `/api/v1/gwangya` => `api/v1/gwangya`

Update Gwangya overall fix

---

src/app/community/gwangya/page.tsx
src/libs/api/axiosInstance.ts

같은 키의 쿠키가 생성되는 현상을 막았습니다.
- axios interceptor에서 gwangyaToken 재발급 시의 쿠키 중복 생성 문제 해결
- 서비스 내에서 하나의 cookie로 gwangyaToken을 관리하기 위해, path에 root를 주었습니다

[hotfix] Prevent duplicated cookie

---

src/libs/api/axiosInstance.ts

- gwangyaToken refresh logic을 추가했습니다.
기존에 광야 리스트 조회가 토큰 만료로 실패하여 401이 반환되면, 
axios response interceptor에서 accessToken 만료 로직이 작동하여 무한 요청이 되고 스크롤이 막히던 현상을 해결했습니다.
- axios response interceptor에서 광야 관련 요청 실패 시의 gwangyaToken refresh 로직을 별도로 분기

[Hotfix] Add gwangyaToken refresh logic

---

src/components/CareerRegistrationBox/index.tsx
src/components/FormItem/Select/index.tsx
src/components/Select/index.tsx
src/components/Select/style.ts
src/pageContainer/register/mentor/index.tsx

멘토 등록 폼 리펙토링을 진행했습니다.
- useGetMyInfo에서 반환되는 data => myInfoData 명칭 변경
- 폼 내에 Select 를 사용하는 모든 컴포넌트를 [Controlled](https://react.dev/reference/react-dom/components/select#props) 방식으로 작동하도록 했습니다
- 컴포넌트에 value를 넘기고 onChange, state로 값을 관리합니다.
- 아래와 제어 컴포넌트에서는 `defaultValue`를 설정할 수 없기에 `defaultValue`가 오직 `option`의 요소로 동작되어 `value`에 `defaultValue`가 할당되어도 정상적으로 선택된 상태가 유지되도록 하였습니다.
- Select의 default 상태의 스타일을 수정했습니다.
- forwardRef가 감싸진 컴포넌트들 내부에서 ref를 사용하지 않고 바로 element에 ref를 할당하는 컴포넌트들의 useForwardRef를 제거했습니다.

Mentor register form refectoring

---

src/apis/mentee/getMyMenteeInfo.ts
src/components/CommunityCard/index.tsx

현재 실제 광야 게시물의 작성 시간과 실제 작성 시간이 9시간 차이가 있는 이슈를 확인할 수 있습니다.
기본적으로 Date는 UTC 기준으로 생성되지만, 브라우저에서는 localtime존에 맞춰서 연산하기 때문에 이런 문제가 생긴 것 같습니다.
z를 제거하여 해결했습니다.

[Hotfix] Update date

---

src/components/TextArea/index.tsx
src/pageContainer/community/board/detail/index.tsx
src/pageContainer/community/board/detail/style.ts

> TextArea 컴포넌트를 게시판 페이지에 추가했습니다.
- TextArea컴포넌트를 comment 타입까지 확장시켰습니다.

Add textArea in boardPage

---

src/app/register/mentee/page.tsx

몇분 전 서비스에 접속 시 갑자기 멘티 정보 등록 페이지로 리다이렉트 되었다는 제보를 받았습니다.
메인 페이지 접속 시 멘티 정보 등록 페이지로 리다이렉트 될 수 있는 경우는 멘티 정보 API 요청 시 404가 반환되는 경우 밖에는 없습니다.
제가 해당 환경에서 테스트 해본 결과 같은 문제가 나타나지 않아 일시적 네트워크 이슈로 판단하였습니다.
그럼에도 이미 멘티 정보가 등록되어있는 사용자가 멘티 정보 등록 페이지에 접속할 여지가 있다는 것은 user flow에 어긋나기 때문에 이에 대한 예외 처리를 했습니다.

Add mentee redirect exception

---

src/apis/mentee/getMyMenteeInfo.ts

> mentee register 페이지에서 무한 리다이렉트 되는 문제를 해결했습니다.
이 전 PR에서 이미 멘티 정보가 등록된 유저에 한해 멘티 정보 등록 페이지 접근을 막으려고 위와 같이 코드를 짰습니다. 이가 연쇄적으로 redirect를 일으켜 오류가 생겼습니다.
실수를 이제서야 알아채고 예외를 추가했습니다.

[Hotfix] Fix menteeRedirectException

---

src/app/community/write/page.tsx
src/components/FormItem/Select/index.tsx
src/pageContainer/community/write/index.tsx
src/pageContainer/community/write/style.ts
src/pageContainer/index.ts

커뮤니티 글 작성 페이지 퍼블리싱을 진행했습니다.
- 커뮤니티의 글 작성 페이지를 퍼블리싱 했습니다.
- select가 동작하지 않는 이유는 `SelectFormItem` 컴포넌트가 react-hook-form 과의 연동에 최적화되게끔 설계하여 단순 마크업만 작성된 지금은 원활하게 동작되지 않습니다.
- 해당 `SelectFormItem` 컴포넌트 사용법 보충을 위해 설명(448957f3b2eec50fad387045ab4c5779f955b66c)을 추가했습니다.

Publishing `community write page`

---

src/components/BoardCard/index.tsx
src/pageContainer/community/board/index.tsx

> boardCard의 클릭 범위를 업데이트 했습니다.
padding까지 포함되도록 카드의 전체 너비로 클릭 범위를 적용시켰습니다.

Update boardCard linkArea

---

src/apis/board/comment/getCommentDetail.ts
src/apis/board/getBoardDetail.ts
src/app/auth/refresh/route.ts
src/app/community/board/[boardId]/[commentId]/page.tsx
src/app/page.tsx
src/app/providers.tsx
src/utils/deleteCookie.ts
src/utils/index.ts

> 공유가 가능하도록 로그인 후 이전 페이지로 리다이렉트 할 수 있도록 했습니다.
요구사항
1.token이 만료된 유저가 /abc path로 접속
2.token 만료 확인 후 refresh -> /auth/signin이동
3.로그인 시 구글 OAuth 페이지로 이동 후 / 루트 페이지로 리다이렉트 (서버 측에서 구현)
4. 이전에 접속한 페이지 ex) /abc가 있을 경우 리다이렉트
4번 기능을 구현하였습니다.
- board와 board comment에서 redirect url을 업데이트했습니다.
- /auth/refresh에서 login 이전 path를 쿠키에 저장합니다. -> 로그인 후 리다이렉트 시 쿠키에 값이 있으면 이동합니다. -> 쿠키를 제거함과 동시에 리다이렉트가 불가능하여 클라이언트 측에서 쿠키를 제거하는 로직을 Provider에 추가했습니다.
아래는 관련 이슈입니다.
https://github.com/vercel/next.js/discussions/48434

[Hotfix] Update redirect that after login

---

src/components/Header/index.tsx

이미지로 프로필을 변경후 기본 프로필 이미지로 변경시 header 프로필이 변경 안되는 문제를 해결하였습니다
https://github.com/themoment-team/GSM-Networking-front/assets/128475660/3322440b-5a43-47e1-b293-9359df2c13a3
- useEffect안에 setProfileUrl 추가

[Hotfix] Profile Update Resolve

---

.storybook/preview.tsx

지금까지 backgrounds 객체의 위치가 잘못되어 있어 지정한 컬러로 배경이 되어있지 않았습니다 그래서 storybook preview.tsx의 backgrounds 객체 위치를 수정했습니다
- backgrounds 객체 위치 수정

[스토리북] 스토리북 backgrounds 객체 위치 수정

---

src/pageContainer/mypage/index.tsx

menteeInfo가 존재하지 않더라도 객체 형태로 반환되기 때문에 if문을 통과하여 userInfo에 저장되는 문제가 있었습니다.
이를 id에 접근하여 유효한 id가 있을 경우 할당하도록 수정했습니다.

[Hotfix] 유저 정보 표시 안되는 오류 해결

---

src/utils/__test__/dateFormat.test.ts

> `pnpm test` 커멘트 실행시 fail 발생
> `pnpm test` 실행시 예상되는 값과 받은 값이 달라서 fail이 발생 되는것 같아
테스트코드의 문제인지, 아니면 호출되는 `parseDateString`함수의 문제인지 확인했습니다
`2024-03-21T15:30:00.000Z` 위와 같은 시간의 경우 UTC기준 2024년 3월 21일 오후 3시 30분
이지만 한국시간이 되기 위해 +9시간을 해야하지 2024년 3월 22일 오전 12시 30분입니다
따라서 테스트코드가 잘못되었다 판단
수정후 PR합니다

fix: 잘못된 테스트 케이스 수정
